#### assign_factor_levels ####

#' Assign Factor Levels to Variables in a Data Frame
#'
#' This function converts specified variables in a dataset into factors with corresponding levels and labels as defined in a separate `data_factor_recode` data frame.
#'
#' @param data A data frame containing the variables to be converted to factors.
#' @param variables A character vector of variable names in `data` that need to be converted into factors.
#' @param data_factor_recode A data frame containing the recoding information with columns `variable` (name of the variable), `level` (factor levels), and `label` (factor labels). Each row defines a level-label pair for a variable.
#' @param new_varname_prefix A character string to be prefixed to the new factor variable names. Default is `NULL`, meaning no prefix is added.
#' @param new_varname_suffix A character string to be suffixed to the new factor variable names. Default is `"_f"`.
#'
#' @return A data frame with new factor variables added, named using the original variable names with the specified prefix and/or suffix. The original variables remain unchanged.
#'
#' @details
#' The function iterates over the list of specified `variables` and checks whether each variable exists in the `data_factor_recode` data frame. For variables found in the recoding data, it creates a new factor variable in the `data` data frame using the provided levels and labels. The new variable name is generated by appending the `new_varname_prefix` and/or `new_varname_suffix` to the original variable name.
#'
#' If a variable is not found in `data_factor_recode`, a message is printed and the function proceeds to the next variable.
#' 
#' The function validates that the number of levels matches the number of labels for each variable. If there is a mismatch, it stops and raises an error.
#' 
#' Warnings or errors during factor conversion are handled using `tryCatch()`, and corresponding messages are displayed.
#'
#' @note The `data_factor_recode` data frame must contain three columns: `variable`, `level`, and `label`. Ensure that the levels and labels are consistent for each variable.
#'
#' @examples
#' # Example usage
#' data <- data.frame(id = 1:5, group = c(1, 2, 1, 3, 2))
#' data_factor_recode <- data.frame(variable = c("group", "group", "group"),
#'                                  level = c(1, 2, 3),
#'                                  label = c("Control", "Treatment A", "Treatment B"))
#' 
#' new_data <- assign_factor_levels(data, variables = c("group"),
#'                                  data_factor_recode = data_factor_recode)
#'
#' @export

assign_factor_levels <- function(data, variables, data_factor_recode, new_varname_prefix=NULL, new_varname_suffix="_f") {
  # Check data_factor_recode include expected columns
  required_columns <- c("variable", "level", "label")
  if (!all(required_columns %in% names(data_factor_recode))) {
    stop("data_factor_recode must contain columns: 'variable', 'level', and 'label'")
  }
  
  # Loop over each variable 
  for (var in variables) {
    ## Check if the variable exists in recode data
    if (!(var %in% data_factor_recode$variable)) {
      cat(paste(var, "not among categorical variables\n"))
      next  ## Skip this iteration if variable not found
    }
    
    # Create the new factor variable name
    factor_var_name <- paste0(new_varname_prefix, var, new_varname_suffix)
    
    # Output levels and their labels
    recode_info <- subset(data_factor_recode, variable == var)
    is_numeric_var <- is.numeric(data[[var]])
    
    ## Handle numeric and non-numeric variables
    factor_levels <- if (is_numeric_var) as.numeric(recode_info$level) else recode_info$level
    factor_labels <- recode_info$label
    
    ## Validate levels and labels length
    if (length(factor_levels) != length(factor_labels)) {
      stop(paste("Mismatch between levels and labels for variable:", var))
    }
    
    # Add the new factor variable with corresponding levels and labels
    data[[factor_var_name]] <- tryCatch({
      factor(data[[var]], levels = factor_levels, labels = factor_labels)
    }, warning = function(w) {
      warning(paste("Issue with factor conversion for", var, ":", w$message))
      return(NA)
    }, error = function(e) {
      stop(paste("Error in factor conversion for", var, ":", e$message))
    })
    
    cat(paste(factor_var_name, "added to data\n"))
  }
  
  return(data)
}

#### load_questionnaire_data ####

#' Load Questionnaire Data with Optional Variable Selection
#'
#' Loads a dataset from a given file path using `data.table::fread`, with the option to select only variables
#' that start with a specified prefix. The `entity_id` column is always retained if present (CLSA participant id).
#'
#' @param path_data Character string. Path to the questionnaire data file (CSV or other format supported by `fread`).  
#' @param keep_var_prefix Optional character string. If specified, only variables whose names start with this prefix
#'   will be retained (along with `entity_id`). Set to `NULL` (default) to retain all variables.  
#' @param ... Parameters to pass to `data.table::fread` 
#' 
#' @importFrom  data.table fread  
#'
#' @return A `data.table` containing the selected variables.  
#' 
#' @examples  
#' \dontrun{
#' load_questionnaire_data("data/questionnaire.csv")
#' load_questionnaire_data("data/questionnaire.csv", keep_var_prefix = "NUT_")
#' }
#'
#' @export
load_questionnaire_data <- function(path_data, keep_var_prefix = NULL, ...) {
  # validate file path
  if (!file.exists(path_data)) {
    stop("File not found at: ", path_data)
  }
  # Load data
  data_questionnaire <- data.table::fread(file = path_data, showProgress = FALSE, ...)
  # if applicable keep only matching variables + 'entity_id'
  if (!is.null(keep_var_prefix)) {
    variables_to_keep <- grep(paste0("^", keep_var_prefix), names(data_questionnaire), value = TRUE)
    # Always keep 'entity_id' + variables identified with prefix
    vars_to_keep <- union("entity_id", variables_to_keep)
    data_questionnaire[, setdiff(names(data_questionnaire), vars_to_keep) := NULL]
  }
  return(data_questionnaire)
}



#### prepare_clsa_questionnaire ####

#' Prepare a Generic CLSA Questionnaire Data from Raw Files and Dictionary
#'
#' Loads and prepares questionnaire data using a raw data file and a structured data dictionary.
#' Supports optional renaming of variables, categorical factor recoding based on levels, and variable labeling.
#'
#' @param dir_data_raw Character. Path to the directory where raw data and dictionary files are stored.
#' @param filename_dic Character. Filename of the Excel data dictionary (must contain sheets "Variables" and "Categories").
#' @param filename_data Character. Filename of the raw data file (CSV or TSV supported by `data.table::fread`).
#' @param original_variable_names Character vector. Names of the original variables to extract.
#' @param new_variable_names Optional character vector. New names for the variables. Required if `do_rename = TRUE`.
#' @param do_rename Logical. Should variables be renamed according to `new_variable_names`? Defaults to `TRUE`.
#' @param show_rename Logical. If `TRUE`, opens a Viewer window to confirm renaming. Defaults to `FALSE`.
#' @param recode_factor Logical. Whether to apply factor level recoding using the dictionary. Defaults to `TRUE`.
#'
#' @return A `data.frame` (technically a `data.table` subclass) with renamed, labelled, and optionally recoded questionnaire variables.
#'
#' @details
#' - The data dictionary Excel file must contain:
#'   - A **"Variables"** sheet with at least columns `name` and `label`.
#'   - A **"Categories"** sheet with at least columns `variable`, `name`, and `label` for factor levels.
#' - Factor variables will be suffixed with `_f` after recoding (e.g., `sex_f`) and labelled.
#'
#' @importFrom readxl read_xlsx
#' @importFrom data.table fread
#' @importFrom dplyr filter select rename inner_join all_of
#' @importFrom tibble tibble deframe
#' @importFrom labelled set_variable_labels var_label
#' @importFrom utils View
#'
#' @seealso [assign_factor_levels()] for recoding factor levels using dictionary definitions.
#'
#' @examples
#' \dontrun{
#' data_prepared <- prepare_clsa_questionnaire(
#'   dir_data_raw = "data/raw",
#'   filename_dic = "dictionary.xlsx",
#'   filename_data = "baseline.csv",
#'   original_variable_names = c("age", "sex", "income"),
#'   new_variable_names = c("age_years", "sex", "income_cat"),
#'   do_rename = TRUE,
#'   show_rename = FALSE,
#'   recode_factor = TRUE
#' )
#' }
#'
#' @export


prepare_clsa_questionnaire <- function(
    dir_data_raw,
    filename_dic,
    filename_data,
    original_variable_names,
    new_variable_names = NULL,
    do_rename = TRUE,
    show_rename = FALSE,
    recode_factor = TRUE
) {
  message("prepare_clsa_questionnaire file: ", filename_data)
  
  # Paths
  path_dic <- file.path(dir_data_raw, filename_dic)
  path_data <- file.path(dir_data_raw, filename_data)
  
  # Check files exist
  if (!file.exists(path_dic)) stop("Dictionary file not found: ", path_dic)
  if (!file.exists(path_data)) stop("Data file not found: ", path_data)
  
  # Check duplicated names
  duplicated_sum_original <- sum(duplicated(original_variable_names))
  if(duplicated_sum_original>0)  {
    message(sprintf("The following %d variable(s) were duplicated in 'original_variable_names':", duplicated_sum_original))
    print(subset(original_variable_names, duplicated(original_variable_names)))
    stop("Duplicated variable names may cause error.")
  }
  duplicated_sum_new <- sum(duplicated(new_variable_names))
  if(duplicated_sum_new>0)  {
    message(sprintf("The following %d variable(s) were duplicated in 'new_variable_names':", duplicated_sum_new))
    print(subset(new_variable_names, duplicated(new_variable_names)))
    stop("Duplicated variable names may cause error.")
  }
  
  # Check renaming conditions
  if (do_rename) {
    if (is.null(new_variable_names)) {
      stop("'new_variable_names' must not be NULL when renaming variables.")
    }
    if (length(original_variable_names) != length(new_variable_names)) {
      stop("Mismatch: 'original_variable_names' and 'new_variable_names' must have equal length.")
    }
    
    data_rename <- tibble::tibble(new_name = new_variable_names, original_name = original_variable_names)
    vector_rename <- tibble::deframe(data_rename)
    
    if (show_rename) {
      data.frame(original = original_variable_names, new = new_variable_names) |> 
        utils::View(title = "data_sd: show_rename")
    }
  }
  
  # Load data
  data_sd <- data.table::fread(file = path_data, showProgress = FALSE)
  
  # Check that all expected variables are present
  missing_vars <- setdiff(original_variable_names, names(data_sd))
  if (length(missing_vars) != 0) {
    message(sprintf("The following %d variable(s) were not found in 'filename_data':", length(missing_vars)))
    print(missing_vars)
    stop("Missing variables in input file.")
  }
  
  # Keep only relevant columns: 'entity_id' + variables of interest
  vars_to_keep <- c("entity_id", original_variable_names)
  data_sd[, setdiff(names(data_sd), vars_to_keep) := NULL]
  
  # Load dictionary: Variables sheet
  if(do_rename || recode_factor) {
    dictionary_sd_var <- 
      readxl::read_xlsx(path_dic, sheet = "Variables") |>
      dplyr::filter(name %in% original_variable_names)
  }
  
  # Rename variables if needed
  if (do_rename) {
    dictionary_sd_var <- 
      dictionary_sd_var |>
      dplyr::rename(original_name = name) |>
      dplyr::inner_join(data_rename, by = "original_name")
    
    data_sd <- 
      data_sd |> dplyr::rename(dplyr::all_of(vector_rename))
  }
  
  # Recode categorical variables (factor levels)
  if (recode_factor) {
    dictionary_sd_cat <- 
      readxl::read_xlsx(path_dic, sheet = "Categories")
    
    if (do_rename) {
      dictionary_sd_cat <- 
        dictionary_sd_cat |>
        dplyr::rename(original_name = variable, level = name) |>
        dplyr::inner_join(dictionary_sd_var |> dplyr::select(original_name, label) |> dplyr::rename(var_label = label), by = "original_name") |>
        dplyr::inner_join(data_rename, by = "original_name")
      
      message("assign_factor_levels:")
      data_sd <- 
        assign_factor_levels(
          data = data_sd,
          variables = dictionary_sd_var$new_name,
          data_factor_recode = dictionary_sd_cat |> dplyr::rename(variable = new_name)
        )
    } else {
      dictionary_sd_cat <- 
        dictionary_sd_cat |>
        dplyr::rename(var_name = variable, level = name) |>
        dplyr::inner_join(dictionary_sd_var |> dplyr::select(name, label) |> dplyr::rename(var_name = name, var_label = label), by = "var_name")
      
      message("assign_factor_levels:")
      data_sd <- 
        assign_factor_levels(
          data = data_sd,
          variables = dictionary_sd_var$name,
          data_factor_recode = dictionary_sd_cat |> dplyr::rename(variable = var_name)
        )
    }
  }
  
  # Apply variable labels
  if (do_rename) {
    var_labels <- setNames(as.list(dictionary_sd_var$label), dictionary_sd_var$new_name)
    factor_var_labels <- setNames(as.list(unique(dictionary_sd_cat$var_label)), paste0(unique(dictionary_sd_cat$new_name), "_f"))
  } else {
    var_labels <- setNames(as.list(dictionary_sd_var$label), dictionary_sd_var$name)
    factor_var_labels <- setNames(as.list(unique(dictionary_sd_cat$var_label)), paste0(unique(dictionary_sd_cat$var_name), "_f"))
  }
  
  data_sd <- data_sd |>
    labelled::set_variable_labels(.labels = var_labels, .strict = FALSE) |>
    labelled::set_variable_labels(.labels = factor_var_labels, .strict = FALSE)
  
  labelled::var_label(data_sd) <- list(entity_id = "Participant id")
  
  return(data_sd)
}


#### output_variable_list ####

#' Extract Variable Names with Specific Prefix
#'
#' This function returns variable names from a data frame that start with a given prefix,
#' optionally excluding variables that match one or more patterns.
#'
#' @param data A data frame from which to extract variable names.
#' @param prefix A character string used to identify variable names starting with this prefix.
#' @param exclude Optional character vector of patterns to exclude from the matched variable names.
#'
#' @return A character vector of variable names from `data` that start with the specified `prefix`
#' and do not match any of the `exclude` patterns (if provided).
#'
#' @examples
#' df <- data.frame(sd_age1 = 1:5, sd_age2 = 6:10, height = 11:15)
#' output_variable_list(df, "sd_")
#' output_variable_list(df, "sd_", exclude = "_age2")
#'
#' @export
output_variable_list <- function(data, prefix, exclude = NULL) {
  if (!is.data.frame(data)) stop("`data` must be a data frame.")
  if (!is.character(prefix) || length(prefix) != 1) stop("`prefix` must be a single character string.")
  if (!is.null(exclude) && !is.character(exclude)) stop("`exclude` must be NULL or a character vector.")
  
  variables <- grep(paste0("^", prefix), names(data), value = TRUE)
  
  if (!is.null(exclude)) {
    pattern_exclude <- paste0(exclude, collapse = "|")
    variables <- variables[!grepl(pattern_exclude, variables)]
  }
  
  return(variables)
}

#### recode_sd_generic ####

#' Prepare sociodemographic or questionnaire prefixed variables with a custom recoding function
#'
#' This generic function identifies variables with a specified prefix, applies a user-defined
#' recoding function to them, optionally renames the variables (removing `"sd_"` prefix),
#' and optionally removes the original and factor variables from the output.
#'
#' @param data A data frame containing the variables to be recoded.
#' @param prefix A character string specifying the prefix to identify target variables (e.g., "sd_").
#' @param recoding_function A function to apply across selected variables
#' @param remove_sd_prefix Logical; if TRUE (default), the "sd_" prefix is removed from recoded variable names.
#' @param remove_original Logical; if TRUE (default), the original variables are removed after recoding.
#'
#' @return A modified data frame containing the recoded variables, optionally renamed and with original variables removed.
#'
#' @seealso \code{\link{output_variable_list}}
#'
#' @importFrom dplyr across mutate select all_of
#' @importFrom glue glue
#'
#' @export
recode_sd_generic <- function(data, prefix, recoding_function = NULL,
                              remove_sd_prefix = TRUE, remove_original = TRUE) {
  if (!is.data.frame(data)) stop("`data` must be a data frame.")
  if (is.null(recoding_function)) stop("Please specify a recoding function using 'recoding_function'.")
  
  # Define new variable names
  new_variables_names <- if (remove_sd_prefix) '{gsub("^sd_", "", .col)}' else '{.col}'
  
  # Get prefixed variables, excluding factor variables ('_f' suffix at the end only)
  variables <- output_variable_list(data, prefix, exclude = c("_f$"))
  
  # Warn if logic is contradictory
  if (!remove_sd_prefix && remove_original) {
    warning("You are keeping original variable names while also removing them — this may cause name collisions.")
  }
  
  # No matching variables
  if (length(variables) == 0) {
    warning(glue::glue("No variables found with prefix '{prefix}' (excluding '_f'). Returning original data."))
    return(data)
  }
  
  # Apply recoding
  data_recoded <- 
    data |>
    dplyr::mutate(
      dplyr::across(
        .cols = dplyr::all_of(variables),
        .fns  = recoding_function,
        .names = new_variables_names
      )
    )
  
  # If needed, remove original variables
  if (remove_original) {
    data_recoded <- data_recoded |>
      dplyr::select(-dplyr::all_of(variables))
  }
  
  return(data_recoded)
}

#### extract_medi_data ####

#' Extract and summarize vitamin/mineral/natural product data
#'
#' This function extracts vitamin/mineral/natural product data from questionnaire
#' variables (prefix `MEDI_ID_NAME_SP_OUT*`), standardizes the text, flags
#' occurrences of user-specified keyword groups (vitamins, minerals, mixed
#' supplements, omega, natural products), and summarizes the results by
#' participant (`entity_id`)
#'
#' @param path_data Character string. Path to the questionnaire data file (CSV or other format supported by `fread`). 
#' @param words_vitamin Character vector of keywords to flag vitamin products
#'   (default = NULL).
#' @param words_mineral Character vector of keywords to flag mineral products
#'   (default = NULL).
#' @param words_mixed Character vector of keywords to flag mixed supplements (eg, multivitamin with both vitamin or minerals)
#'   (default = NULL).
#' @param words_omega Character vector of keywords to flag omega supplements (eg, 3-6-9, fish oil)
#'   (default = NULL).
#' @param words_natural Character vector of keywords to flag natural products (eg, antioxydant, herbal mix)
#'   (default = NULL).
#' @param return_long Logical. If true, return the long-coded data with full supplement name. Default = FALSE.
#' @param show_progress Logical. If true, show recoding progression. Default = FALSE.
#'
#' @return By default, a `data.table` in wide format with one row per `entity_id`
#'   and columns `flag_*` summarizing the number of vitamin/mineral/natural product
#'   containing the keywords. If called with `return_long = TRUE`, returns a list
#'   with two elements:
#'   \describe{
#'     \item{wide}{Summarized flags by `entity_id`}
#'     \item{long}{Melted table with per-medication flags}
#'   }
#'
#' @seealso [load_questionnaire_data()] to load questionnaire data with optional variable selection
#' 
#' @examples
#' \dontrun{
#' DT <- extract_medi_data(path_data,
#'                         words_vitamin = c("vitamin", "multivitamin"),
#'                         words_omega   = c("omega", "fish oil"))
#' }
#'
#' @export
extract_medi_data <- function(
    path_data, 
    words_vitamin = NULL, 
    words_mineral = NULL, 
    words_mixed   = NULL, 
    words_omega   = NULL, 
    words_natural = NULL,
    return_long   = FALSE,
    show_progress = FALSE
) {
  if(show_progress) message("extract_medi_data: loading data")
  # Load questionnaire data. Aux. function in ./dir_scripts/prepare_clsa_questionnaire.R
  data_medi_raw <- 
    load_questionnaire_data(
      path_data, 
      keep_var_prefix = "MEDI_ID_NAME_SP_OUT")
  
  # Rename MEDI_ID columns to medi_1, medi_2, ...
  data.table::setnames(
    data_medi_raw,
    old = names(data_medi_raw)[-1],
    new = paste0("medi_", seq_len(ncol(data_medi_raw) - 1)),
    skip_absent = TRUE)
  
  # Transpose wide to long
  data_medi_raw_t <- 
    data.table::melt(
      data = data_medi_raw, 
      id.vars = "entity_id",
      value.name = "value",
      na.rm = TRUE)
  
  # Standardize text (remove white space begin/end, change double to single)
  data_medi_raw_t[, value := toupper(stringr::str_squish(value))]
  data_medi_raw_t <- data_medi_raw_t[value != "", ]
  
  # Word groups as named list
  word_groups <- list(
    vitamin = words_vitamin,
    mineral = words_mineral,
    mixed   = words_mixed,
    omega   = words_omega,
    natural = words_natural
  )
  
  # Aux. function to flag words
  is_word_present <- function(string, words) {
    if (is.null(words)) return(rep(FALSE, length(string)))
    escaped <- stringr::str_replace_all(words, "([\\W])", "\\\\\\1")
    pattern <- paste0("\\b(", paste(escaped, collapse = "|"), ")\\b")
    grepl(pattern, string, ignore.case = TRUE)
  }
  
  # Identify any word from each string, creating dummy variable for each row (each reported MEDI for each participant, long/tall data)
  if(show_progress) message("extract_medi_data: flagging words ", appendLF = FALSE)
  for (grp in names(word_groups)) {
    if(show_progress) message(".", appendLF = FALSE)
    data_medi_raw_t[, paste0("flag_", grp) := 
                      as.integer(is_word_present(value, word_groups[[grp]]))]
  }
  
  # Summarise flag across all rows (medication number) by participant id, changing data from long to wide
  ## auto-selected flag variables
  flag_variables <- grep("^flag_", names(data_medi_raw_t), value = TRUE)
  ## sum across 'flag_*' variables
  data_medi_flag_w <- data_medi_raw_t[, lapply(.SD, sum), by = entity_id, .SDcols = flag_variables]
  
  # Restore original variable names for tracking purpose
  data_medi_raw_t[, variable := gsub("medi", "MEDI_ID_NAME_SP_OUT", variable)]
  
  if(show_progress)  message("Done!")
  
  # Return output
  if (return_long) {
    return(list(wide = data_medi_flag_w, long = data_medi_raw_t))
  } else {
    return(data_medi_flag_w)
  }
}

